feat: udistrital/sga_documentacion#87  Migración del módulo de plan de estudios a arquitectura de micro cliente
udistrital/sga_cliente_plan_estudios_mf pull request #1
Opened 2024-03-05 12:40 UTC by andresFLZ

2024-03-08 14:48 UTC, NeFaWaltPint commented on src/app/components/summary-planes-estudio/summary-planes-estudio.component.html
Mmmm aquí es preferible dejar la ruta relativa, ya en linea localhost:4211 sería inalcanzable.

2024-03-08 14:59 UTC, NeFaWaltPint commented on src/assets/i18n/en.json
Está cruzado, el título dice **en.json** pero el contenido está en español.

2024-03-08 15:10 UTC, NeFaWaltPint commented on src/assets/i18n/es.json
Está cruzado, el título dice **es.json** pero el contenido está en inglés.
Adicionalmente faltan estas etiquetas de traducción:
```json
{
    "GLOBAL": {
        "admitiendo_aspirantes": "Admitiendo aspirantes",
        "agregar_empresa": "Empresa",
        "agregar_universidad": "Universidad",
        "aspirantes_admitidos": "aspirantes admitidos",
        "aspirantes_correctamente": "aspirantes correctamente",
        "confirme_numero_registro": "CONFIRME el Número del registro del ICFES (SNP)",
        "fecha": "Fecha",
        "fecha_expedicion": "Fecha de expedición del documento",
        "info_contacto": "Información de contacto",
        "info_familiar": "Información familiar",
        "institucion": "Institución",
        "limpiar": "Limpiar",
        "numero": "Número",
        "numero_registro": "Número del registro del ICFES (SNP)",
        "placeholder_confirme_numero_registro": "Ej: Número del registro del ICFES",
        "placeholder_fecha_expedicion": "Ej: 05/05/2013",
        "placeholder_numero_registro": "Ej: Número del registro del ICFES",
        "placeholder_tipo_colegio": "Ej: Oficial",
        "placeholder_tipo_icfes": "Ej: Tipo de ICFES",
        "placeholder_valido_colegio": "Ej: No",
        "proceso_admision_exitoso": "Proceso de admisión exitoso",
        "programa": "Programa",
        "se_admitieron": "Se admitieron",
        "se_admitiran": "Se admitirán",
        "tipo_colegio": "Tipo de Colegio donde culminó el Grado 11",
        "tipo_icfes": "Tipo de ICFES",
        "valido_colegio": "¿Validó el bachillerato?"
    },
    "inscripcion": {
        "no_fechas_inscripcion": "El proyecto curricular seleccionado no presenta fechas de inscripcion"
    },
    "ptd": {
        "aprobacion_preasignacion": "Preasignación aprobada con exito",
        "ptd_docente_principal": "PTD Docente principal",
        "ptd_docente_relacionado": "PTD Docente relacionado",
        "ptd_general": "PTD General",
        "ptd_timed": "PTD por Tiempos"
    }
}
```

2024-03-08 15:11 UTC, NeFaWaltPint requested changes
Los archivos de traducción están cruzados en nombre y faltan unas etiquetas. El url a una imagen está con localhost:puerto, la idea es que la ruta quede relativa. Demás Ok.

2024-03-10 23:56 UTC, andresFLZ commented
Se corrigieron los errores de nombres cruzados, quise dejar la ruta relativa pero desde el cliente root no puede acceder a los assets del microfront, con las demas imagenes que se usan en micro clientes se usa la ruta: 

* basePathAssets = 'https://pruebasassets.portaloas.udistrital.edu.co/';

Por lo que decidí hacerlo como las demas imagenes estan implementadas.

2024-04-05 13:43 UTC, merged